# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Manuscripts, algorithms, and more
email: elli.bleeker@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Postdoctoral researcher at the Royal Dutch Academy of Arts and Sciences; PhD in Digital Humanities. Equally fascinated by old manuscripts as well as the algorithms to study them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ellibleeker.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ellibleeker
github_username:  bleekere

display_footer: none  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: "Mapping Invention in Writing"
project_one_description: 
project_one_url: url
# project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: "Text Modeling"
project_two_description: description here
project_two_url: url
# project_two_icon: photo_camera


project_three: "Automated Collation"
project_three_description: description here
project_three_url: url
# project_three_icon: hotel


project_four: "Forgotten Writers"
project_four_description: Uncovering the writers that history forgot.
project_four_url: url
# project_four_icon: restaurant

# Build settings
markdown: kramdown
theme: jekyll-material-theme
permalink: pretty
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-minifier
  icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/bleekere

syntax_highlighting: true # include the css for syntax highlighting


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
